//! T049 — `AudioAnalyzerPort` contract. The in-memory fake always runs; the real
//! symphonia + libKeyFinder + aubio adapter runs only under `--features real-adapters` (needs the
//! native libraries: `brew install libkeyfinder aubio`, verified by `scripts/check-system-libs.sh`).
//!
//! The real-adapter tests below assert against fixtures whose ground truth is arithmetic (a C-major
//! triad; a click every 0.5s = 120 BPM), generated by `support::wav_fixture`. They check that the
//! adapter reads audio it cannot misread — decoding, the Camelot mapping, the tempo estimate and the
//! silence path are all real. They are NOT a claim about accuracy on real music: research.md R4 asks
//! for a pilot against known-key tracks cross-checked with Mixxx, which is a human step (see
//! `vendor/libkeyfinder-sys/README.md`).

mod support;

use application::testkit::stub_audio_analyzer::StubAudioAnalyzer;

#[test]
fn in_memory_analyzer_honors_contract() {
    let analyzer = StubAudioAnalyzer::typical();
    // The fake never opens the file, so any path exercises the contract it can honor: determinism.
    support::audio_analyzer_suite(&analyzer, std::path::Path::new("/does/not/matter.mp3"));
}

#[cfg(feature = "real-adapters")]
mod real {
    use super::support;
    use super::support::wav_fixture;

    use adapters::libkeyfinder_aubio_audio_analyzer::LibkeyfinderAubioAudioAnalyzer;
    use application::ports::audio_analyzer::{AnalyzeError, AudioAnalyzerPort};
    use domain::audio::TempoAmbiguity;

    /// Long enough for libKeyFinder's chromagram and aubio's beat tracker to have real data.
    const FIXTURE_SECONDS: f32 = 20.0;

    #[test]
    fn real_analyzer_honors_contract() {
        let dir = tempfile::tempdir().expect("temp dir");
        let path = wav_fixture::fixture_file(
            dir.path(),
            "triad.wav",
            &wav_fixture::c_major_triad(FIXTURE_SECONDS, 0.7),
        );
        support::audio_analyzer_suite(&LibkeyfinderAubioAudioAnalyzer::new(), &path);
    }

    /// The known-key fixture: C4+E4+G4 is C major, which is Camelot 8B (research.md R4). This is the
    /// one assertion that proves the whole key path — decode, libKeyFinder FFI, and the mapping
    /// table — agrees end to end, rather than each piece merely compiling.
    #[test]
    fn a_c_major_triad_analyzes_as_camelot_8b() {
        let dir = tempfile::tempdir().expect("temp dir");
        let path = wav_fixture::fixture_file(
            dir.path(),
            "c-major.wav",
            &wav_fixture::c_major_triad(FIXTURE_SECONDS, 0.7),
        );

        let features = LibkeyfinderAubioAudioAnalyzer::new()
            .analyze(&path)
            .expect("analyze the triad");

        assert_eq!(
            features.key.map(|key| key.to_string()),
            Some("8B".to_owned()),
            "a C major triad must map to Camelot 8B"
        );
    }

    /// Silence has no tempo, no key and no energy — it must be reported as such, never as a track
    /// with a fabricated 0 BPM (Principle I).
    #[test]
    fn silence_is_reported_as_silence() {
        let dir = tempfile::tempdir().expect("temp dir");
        let path = wav_fixture::fixture_file(
            dir.path(),
            "silence.wav",
            &wav_fixture::silence(FIXTURE_SECONDS),
        );

        let error = LibkeyfinderAubioAudioAnalyzer::new()
            .analyze(&path)
            .expect_err("silence must not analyze");

        assert!(matches!(error, AnalyzeError::Silence));
    }

    /// The tempo fixture: a click every 0.5s is 120 BPM by arithmetic. Beat tracking is an estimate,
    /// so the assertion allows a few BPM of slack — the point is that the adapter reads the tempo
    /// that is actually there, and reports no doubt about an ordinary one (FR-031).
    #[test]
    fn a_120_bpm_click_track_analyzes_as_120_bpm() {
        let dir = tempfile::tempdir().expect("temp dir");
        let path = wav_fixture::fixture_file(
            dir.path(),
            "click-120.wav",
            &wav_fixture::click_track(FIXTURE_SECONDS, 120.0),
        );

        let features = LibkeyfinderAubioAudioAnalyzer::new()
            .analyze(&path)
            .expect("analyze the click track");

        assert!(
            features.bpm.abs_diff(120) <= 3,
            "expected ~120 BPM, got {}",
            features.bpm
        );
        assert_eq!(features.tempo_ambiguity, TempoAmbiguity::Confident);
    }

    /// A file that is not audio must surface as a decode failure — the reported skip the use case
    /// turns into "this track keeps its metadata-only classification" (Principle III).
    #[test]
    fn a_non_audio_file_is_a_decode_error() {
        let dir = tempfile::tempdir().expect("temp dir");
        let path = dir.path().join("not-audio.mp3");
        std::fs::write(&path, b"this is not audio").expect("write");

        let error = LibkeyfinderAubioAudioAnalyzer::new()
            .analyze(&path)
            .expect_err("a text file must not analyze");

        assert!(matches!(error, AnalyzeError::Decode { .. }));
    }

    /// Energy is a loudness reading, so a quiet master must measure below a loud one. This pins the
    /// direction of the scale — an inverted mapping would file peak-time tracks as warmups.
    #[test]
    fn a_quieter_master_measures_lower_energy() {
        let dir = tempfile::tempdir().expect("temp dir");
        let analyzer = LibkeyfinderAubioAudioAnalyzer::new();
        let loud = wav_fixture::fixture_file(
            dir.path(),
            "loud.wav",
            &wav_fixture::c_major_triad(FIXTURE_SECONDS, 0.9),
        );
        let quiet = wav_fixture::fixture_file(
            dir.path(),
            "quiet.wav",
            &wav_fixture::c_major_triad(FIXTURE_SECONDS, 0.2),
        );

        let loud_energy = analyzer.analyze(&loud).expect("analyze loud").energy;
        let quiet_energy = analyzer.analyze(&quiet).expect("analyze quiet").energy;

        assert!(
            quiet_energy < loud_energy,
            "quiet {quiet_energy:?} should measure below loud {loud_energy:?}"
        );
    }
}
